### ISSUE TITLE
Watchdog should create a default server config.toml

### ISSUE THREAD

**Issue by metalgearsloth** [space-wizards/SS14.Watchdog#15]
I tried running master on windows fresh and got this:
```
System.IO.FileNotFoundException: Could not find file 'E:\Programming\SS14.Watchdog\SS14.Watchdog\bin\instances\syndicate_mothership\config.toml'.
File name: 'E:\Programming\SS14.Watchdog\SS14.Watchdog\bin\instances\syndicate_mothership\config.toml'
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptio
ns options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at Nett.Toml.ReadFile(String filePath, TomlSettings settings)
   at Nett.Toml.ReadFile(String filePath)
   at Robust.Shared.Configuration.ConfigurationManager.LoadFromFile(String configFile) in /home/runner/work/space-station-14/space-station-14/RobustToolbox/Robust.Shared/Conf
iguration/ConfigurationManager.cs:line 46
```

**Comment by metalgearsloth** [comment]
May also be a robust issue instead.
